Partial Issue #19 Automated run and asserts of automated refactoring on the samples
Fixed the code.

Now hitting another problem:
java.lang.RuntimeException: Unexpected exception
	at org.autorefactor.ui.AutoRefactorHandler.applyRefactorings(AutoRefactorHandler.java:435)
	at org.autorefactor.ui.AutoRefactorHandler.access$3(AutoRefactorHandler.java:362)
	at org.autorefactor.ui.AutoRefactorHandler$ApplyRefactoringsJob.testWithSamples(AutoRefactorHandler.java:179)
	... 51 more
Caused by: java.lang.IllegalArgumentException: This API can only be used if the AST is created from a compilation unit or class file
	at org.eclipse.jdt.core.dom.rewrite.ASTRewrite.rewriteAST(ASTRewrite.java:272)
	at org.autorefactor.ui.AutoRefactorHandler.applyRefactorings(AutoRefactorHandler.java:404)